inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0.4
  Exclude:
    - db/schema.rb
    - bin/*
    - config/initializers/*
    - vendor/**/*

Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Lint/MissingSuper:
  Enabled: false
Style/RedundantFetchBlock:
  Enabled: false

